services:
  warp:
    build:
      context: ./warp-cli
      dockerfile: Dockerfile
    image: warp_cli_proxy
    container_name: warp-proxy
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    volumes:
      - ${WARP_DATA}:/var/lib/cloudflare-warp
    environment:
      - TZ=Europe/Helsinki
    restart: unless-stopped
    networks:
      - 3xui-net

  3xui-alt:
    build:
      context: ./3x-ui
      dockerfile: Dockerfile
    image: 3xui_app:latest
    container_name: 3xui-app
    volumes:
      - ${DB}:/etc/x-ui/
      - ${CERT}:/root/cert/
    environment:
      XRAY_VMESS_AEAD_FORCED: "false"
      XUI_ENABLE_FAIL2BAN: "true"
      TZ: Europe/Amsterdam
    tty: true
    ports:
      # Веб-панель доступна только с localhost (для SSH туннеля)
      - "127.0.0.1:${PANEL_PORT}:${PANEL_PORT}"
      # Прокси-трафик доступен извне
      - "${HTTPS_OUT_PORT}:443"
    networks:
      - 3xui-net
    restart: unless-stopped

networks:
  3xui-net:
    external: true